spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update

lock-examples:
  execution-mode: move-data